# Generated by Django 3.1.5 on 2021-02-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlab', '0002_auto_20210126_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='member',
        ),
        migrations.AddField(
            model_name='workspace',
            name='user',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
