# Generated by Django 3.1.5 on 2021-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlab', '0003_auto_20210202_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
