# Generated by Django 3.1.5 on 2021-03-02 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlab', '0004_project_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 14, 32, 54, 341210)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workspace',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 2, 14, 33, 13, 43089)),
            preserve_default=False,
        ),
    ]
