# Generated by Django 3.1.5 on 2021-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlab', '0005_auto_20210302_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
