# Generated by Django 3.1.5 on 2021-04-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectlab', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='save_desc',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
